/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Checklist = IDL.Record({
  'customerName' : IDL.Text,
  'technicianName' : IDL.Text,
  'date' : IDL.Int,
  'vehicleModel' : IDL.Text,
  'vehicleStatus' : IDL.Text,
  'batteryStatus' : IDL.Text,
});
export const ChecklistInput = IDL.Record({
  'customerName' : IDL.Text,
  'technicianName' : IDL.Text,
  'vehicleModel' : IDL.Text,
  'vehicleStatus' : IDL.Text,
  'batteryStatus' : IDL.Text,
});

export const idlService = IDL.Service({
  'getChecklist' : IDL.Func([IDL.Int], [Checklist], ['query']),
  'getRecentChecklists' : IDL.Func([IDL.Nat], [IDL.Vec(Checklist)], ['query']),
  'saveChecklist' : IDL.Func([ChecklistInput], [IDL.Int], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Checklist = IDL.Record({
    'customerName' : IDL.Text,
    'technicianName' : IDL.Text,
    'date' : IDL.Int,
    'vehicleModel' : IDL.Text,
    'vehicleStatus' : IDL.Text,
    'batteryStatus' : IDL.Text,
  });
  const ChecklistInput = IDL.Record({
    'customerName' : IDL.Text,
    'technicianName' : IDL.Text,
    'vehicleModel' : IDL.Text,
    'vehicleStatus' : IDL.Text,
    'batteryStatus' : IDL.Text,
  });
  
  return IDL.Service({
    'getChecklist' : IDL.Func([IDL.Int], [Checklist], ['query']),
    'getRecentChecklists' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(Checklist)],
        ['query'],
      ),
    'saveChecklist' : IDL.Func([ChecklistInput], [IDL.Int], []),
  });
};

export const init = ({ IDL }) => { return []; };